# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

sudo: false
arch: amd64
os: linux
# Ubuntu 20.04 (Focal Fossa) on travis does not support openjdk 8
# see https://github.com/travis-ci/docs-travis-ci-com/issues/2902
dist: bionic
language: java

cache:
  directories:
  - $HOME/.m2

services:
  - docker

# We have to install correct JDK as Travis CI installs dependencies before our script
# see https://docs.travis-ci.com/user/languages/java/#maven-dependency-management
jdk:
  - openjdk8

script:
  - ./build_ranger_using_docker.sh mvn clean test
